# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cubical_compute <- function(data, dims, maxdim = 3L, top_dim = FALSE, embedded = FALSE, threshold = 9999) {
    .Call(`_ripserr_cubical_compute`, data, dims, maxdim, top_dim, embedded, threshold)
}

ripser_cpp_dist <- function(dataset, dim, thresh, ratio, p) {
    .Call(`_ripserr_ripser_cpp_dist`, dataset, dim, thresh, ratio, p)
}

